### ISSUE TITLE
Placement in Layout ?

### ISSUE THREAD

**Issue by MentalGear** [antoniandre/splitpanes#104]
First off, thanks for this amazing feature packed and intuitive library!
Now my question: Would you recommend to put splitpanes within a layout of a nuxt app, or on a page ?
Thank you !

**Comment by antoniandre** [comment]
Hi @MentalGear, thanks for the feedback.
What do you mean bey layout or page, do you mean SSR or client side?

No sure that's what you are talking about, Splitpanes will work on client side as it needs to manipulate the DOM, but it will trigger from the mounted hook so it should not be a problem in SSR.
It would only make sense if you have a lot of contents inside the panes to pre-render.

If your question is not about that can you specify?

**Comment by antoniandre** [comment]
Closing the issue now, please reopen if not solved.

**Comment by gfrancis86** [comment]
Hi! I am trying to use this on a nuxt project and I'm getting: this.$slots.default is not a function
which I assume is because it's using ssr (nuxt)
I want to use a simple:

<splitpanes class="default-theme" horizontal>
    <pane></pane>
    <pane></pane>
    <pane></pane>
  </splitpanes>

I installed the package using: npm install splitpanes@next --save
I import the components on my page.vue
I don't know what I'm missing :(

**Comment by hnviradiya** [comment]
I am also having this issue. I am using nuxt. But not SSR. Still having issue. Older version of splitpanes was working fine.
