### ISSUE TITLE
Scrollbar inside panel

### ISSUE THREAD

**Issue by kostaspapad** [antoniandre/splitpanes#19]
I would like to use the css attr overflow: auto to one of the panels, I put the attr to the css .splitpanes__pane class but it is not working, any idea why?

**Comment by antoniandre** [comment]
Hi @kostaspapad,
The `overflow: auto` is absolutely possible on on a pane, just add this rule:

```css
.splitpanes__pane {
    overflow: auto;
}
``` 

Also make sure it is not overridden by another rule.

![image](https://user-images.githubusercontent.com/22971289/52929458-9e932600-3398-11e9-8d07-e4ee241f1f41.png)

**Comment by kostaspapad** [comment]
Yes thank you

**Comment by hnviradiya** [comment]
seems. there is something wrong still. vertical scrollbar is showing up and horizontal scrollbar is not working. Obviously should be fixed with css only and cannot be issue with splitpanes. but not able to figure out, what strange is happening. 

I have edited your codepen to following.

https://codepen.io/hnviradiya/pen/JjPyvxx

where overWidth class is having 3000px width and still not showing horizontal scroll with following style.

.splitpanes__pane{
  overflow: auto;
}
