### ISSUE TITLE
Resize reversed after prepend pane via v-if

### ISSUE THREAD

**Issue by kuznetz** [antoniandre/splitpanes#67]
Example: https://codepen.io/kuznetz/pen/abbMREP

**Comment by antoniandre** [comment]
Thanks for reporting @kuznetz, 
A quick way around it until I look into it is to add the pane with the v-if after the first one: https://codepen.io/antoniandre/pen/XWWwKxL

And another alternative to v-if here: https://codepen.io/antoniandre/pen/poombWZ

**Comment by petersutter** [comment]
I also have the same issue

**Comment by antoniandre** [comment]
Hi folks, I am currently working on it, will let you know when fixed.

**Comment by amir20** [comment]
It doesn't seem to have fixed the problem for me. See #74 for screenshot.

**Comment by antoniandre** [comment]
Hi everyone, this issue should now be fixed in version 2.2.0.
The remaining issue reported by @amir20 is actually another one after this one. 
So toggling a pane with `v-if` should work.

Please let me know.

btw @kuznetz, in your Codepen, the markup line `splitpanes.default-theme vertical` should be ` splitpanes.default-theme(vertical)`, which is actually the same as `splitpanes.default-theme` as vertical is the default direction.
