### ISSUE TITLE
No initial resized event

### ISSUE THREAD

**Issue by tigerbook73** [antoniandre/splitpanes#80]
I initialize an OpenLayer map instance in one pane in mounted() method, the width of the map is incorrect. I tried to resize the map in the event handler of ready() and resized(), it did not work. (If resize the pane manually after initialized, resize event works)

template:
```
<splitpanes class="default-theme" style="height: 100%" @resized="updateSize" @ready="ready">
        <pane min-size="30" size="80" style="height: 100%">
          <div id="map"></div>
          </div>
        </pane>
        <pane size="20">
          <span>3</span>
        </pane>
</splitpanes>
```
After debug, I found the sequences are:
1. The pane is set to 50% width (there is two panes) 
2. ready event
3. resize event , with event = "undefined"
4. mounted(), where map is initialized
5. pane is set to 80% width
6. no further ready or resize event.

Is it possible to stop initial animation or have an event when the initial pane size is finalized.

**Comment by antoniandre** [comment]
Hi @tigerbook73,
The panes sizes are calculated on mounted, here is the sequence from the codebase:

```js
mounted () {
    this.container = this.$refs.container
    this.checkSplitpanesNodes()
    this.redoSplitters()
    this.resetPaneSizes()
    this.$emit('ready')
    this.ready = true
  }
```

That means that anything you do based on pane size before mounted and before splitpanes fires `ready` will be inaccurate.

If you want to remove the initial transition it's very easy: 
```css
.splitpanes .splitpanes__pane {transition: none;}
```

By default the transition is set to 0.2s you can override that if you want with the above selector.
There is no point to have a callback triggered from splitpanes after the animation since the user may override this 0.2s transition in CSS.

I hope it makes sense!

**Comment by tigerbook73** [comment]
Hi @antoniandre ,

Turn off transition works for me. What I need is to use another setTimeout(0) to resize the map object in mounted() method.

Thank You

One possible improvement:
Currently there is no "resized" event during initial resizing. When transition is enabled, maybe it is possible to catch "transitionend" event and fire a "resized" event.
